language: python

python:
  - "3.5"

sudo: required

services:
  - docker

before_install:
  - docker-compose -v
  - docker -v

install:
  - pip install codecov

script:
  - docker-compose up --build

after_success:
  - codecov

env:
  - PYTHON3_VERSION=3.5
  - PYTHON3_VERSION=3.6
