sudo: required

language: python

python:
  - "3.5"

env:
  - PYTHON3_VERSION=3.5
  - PYTHON3_VERSION=3.6

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
  - apt-get update
  - apt-get install docker-ce
  - rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v
  - docker -v
  - printenv

install:
  - pip install codecov

script:
  - docker-compose up --build

after_success:
  - codecov
